<!-- TITLE -->
<h1 class="MenuH1">Les animaux fantastiques et du quotidien</h1>

<!-- INTRO -->
<section class="introductionC">
    <h2>
        Dans ce glossaire, vous trouverez quelques exemples de créatures féériques et fantastiques vivant dans cet univers. Vous en 
        reconnaisserez sans doute car il y a des créatures et autres animaux dit "classique" des jeux de rôle, jeux vidéos et romans fantaisies. 
        Toutefois, vous pourrez aussi en croiser et lire des descriptions de créatures inventées pour cet univers. 
    </h2>
</section>

<!-- SECTION -->
<section class="sectionCreature">
    <!-- ARTICLE PHALLIOU -->
    <h2>Le Phalliou</h2>
    <article class="artCreature">

        <img src="img\bestiaire\Phalliou.png">

        <p>
            Créature adorable qui ravira le coeur de ces dames. Le Phalliou est un adorable mélange entre un chat et une phalène.
            De la taille d'un chat domestique, cet adorable compagnon se nourrit de poisson, d'eau et de pollen. On conseille de l'eau 
            sucrée comme gourmandise. Il est terriblement joueur et il est particulièrement actif de nuit. Le jour, il passera la majorité 
            du temps à dormir. On appelle le bébé du Phalliou, un Phalinou.     
        </p>

        <div class="divTemoin">
            <h3>"Oh ma fifille ! C'est qui le beau phalliou ? C'est toi ? Oui, c'est toi !"</h3>
            <h4>Juju à Freya, son phalinou</h4>
        </div>
    </article>

    <!-- ARTICLE COUREUR -->
    <h2>Le coureur des Près</h2>
    <article class="artCreature">

        <img src="img\bestiaire\Coureur.png">

        <p>
            De la taille d'une poule, le Coureur des Près est un animal prisé par les fermiers et les éleveurs. Sa viande et son cuir ainsi que 
            ses oeufs sont particulièrement recherchés et c'est un animal central dans l'agriculture et l'élevage. C'est un animal commun très 
            amical à contrario du Coureur de Proie qui est un prédateur dangereux des Rocailles Arides.
        </p>

        <p>
            Les goules sont d'origines humaines, il s'agissait d'individus qui dévoraient les cadavres humains, faute de trouver autre chose 
            pour se nourrir. Les années à vivre reclus ont donnés ces créatures sortant de tout bon cauchemars d'enfants et qui ne reste d'humain
            que leur cruauté, remplaçant le reste par un instinct de tueur et un comportement bestial. Ce sont des nécrophages dangereux qui 
            n'hésitent pas à attaquer tout individu qui s'approche d'eux. Elles vivent dans les cimetières pour manger les corps et saccager les 
            sépultures.
        </p>

        <div class="divTemoin">
            <h3>"Allez les coucous, c'est l'heure de manger ! Dédé, tu grossis mon grand. Bientôt, on te mangera !"</h3>
            <h4>Un éleveur à Dédé, le Coureur de Près, qui regrettre ses choix de vie</h4>
        </div>
    </article>
</section>

<h1 class="MenuH1">La suite du bestiaire prochainement !</h1>