<main>
    <!--POLICE-->
    <h1 class="h1Contact">Posez vos questions aux maîtres du jeu</h1>
    
    <!--FORMULAIRE CONTACT-->
    <section class="formContact">
        <form action="/mon formulaire de contact" method="post">
            <div>
                <label for="Pseudo">Pseudo :</label>
                <input type="text" id="firstname" name="user_firstname">
            </div>
            <div>
                <label for="mail">e-mail :</label>
                <input type="email" id="mail" name="user_mail">
            </div>
            <div>
                <label for="msg">Message :</label>
                <textarea id="msg" name="user_message"></textarea>
            </div>
            <button type="button" id="buttonForm">Envoyer</button>
        </form>
    </section>

    <!--LIENS HYPERTEXTE LOGO-->
    <section class="h2Contact">
        <h2>N'hésitez pas à nous rejoindre sur ces plateformes</h2>
    </section>
    
    <section class="logoContact">
        <div class="discord">
            <a href="https://discord.gg/Gx846WZS">
                <img src="img\logo\discord.png" width="112px" height="112px">
            </a>
        </div>
        <div class="roll20">
            <a href="https://discord.gg/Gx846WZS">
                <img src="img\logo\dice.png" width="112px" height="112px">
            </a>
        </div>
        <div class="twitter">
            <a href="https://app.roll20.net/campaigns/details/7737395/call-of-helheim">
                <img src="img\logo\twitter.png" width="112px" height="112px">
            </a>
        </div> 
    </section>
</main>