<!-- TITLE -->
<h1 class="MenuH1">Les créatures hostiles et dangereux</h1>

<!-- INTRO -->
<section class="introductionC">
    <h2>
        Dans ce glossaire, vous trouverez quelques exemples de créatures hostiles vivant dans cet univers. Vous en reconnaisserez sans doute car
        il y a des créatures et autres animaux dit "classique" des jeux de rôle, jeux vidéos et romans fantaisies. Toutefois, vous pourrez aussi 
        en croiser et lire des descriptions de créatures inventées pour cet univers. 
    </h2>
</section>

<!-- SECTION -->
<section class="sectionCreature">
    <!-- ARTICLE GOBELIN -->
    <h2>Le gobelin</h2>
    <article class="artCreature">

        <img src="img\bestiaire\Gobelin.png">

        <p>
            De petite taille, une peau verte, des yeux rouges, des dents jaunâtres et une voix criarde désagréable au possible, les gobelins
            sont des créatures perfides qui possèdent une espérance de vie assez courte mais qui la compense par leur prolifération digne des 
            vermines les plus tenaces de Mundos. Capable de penser de manière limitée, ils ne répondent qu'à leurs plus bas instinct. Ils 
            savent construire des outils, des armes et des moyens rudimentaires.
        </p>

        <div class="divTemoin">
            <h3>"Le problème du Gobelin est qu'il est toujours au pluriel."</h3>
            <h4>Témoignage d'un aventurier en hebre</h4>
        </div>
    </article>

    <!-- ARTICLE GOULE -->
    <h2>La goule</h2>
    <article class="artCreature">

        <img src="img\bestiaire\Goule.png">

        <p>
            Cauchemar de tout fossoyeur, la Goule ressemble à un humain se déplaçant sur ses quatre pattes bestiales, ces dernières se
            terminent par de longues griffes jaunes porteuses de maladies. Son corps est presque dénué de peau et dévoile ses muscles puissants
            taillés pour la vitesse et les attaques surprises.  Sa gueule est garnie de crocs pointues qui recèlent tant de lambeaux de chairs 
            et d'asticots que bien des aventuriers se sont mis à vomir rien qu'en voyant la tête d'une de ces créatures.
        </p>

        <p>
            Les goules sont d'origines humaines, il s'agissait d'individus qui dévoraient les cadavres humains, faute de trouver autre chose 
            pour se nourrir. Les années à vivre reclus ont donnés ces créatures sortant de tout bon cauchemars d'enfants et qui ne reste d'humain
            que leur cruauté, remplaçant le reste par un instinct de tueur et un comportement bestial. Ce sont des nécrophages dangereux qui 
            n'hésitent pas à attaquer tout individu qui s'approche d'eux. Elles vivent dans les cimetières pour manger les corps et saccager les 
            sépultures.
        </p>

        <div class="divTemoin">
            <h3>"Prends ta pelle, une goule a encore saccagé la tombe de Papi. C'est la troisième fois cette saison !"</h3>
            <h4>Un fermier en colère</h4>
        </div>
    </article>

    <!-- ARTICLE CUIRASSÉ -->
    <h2>Le Poisson Cuirassé</h2>
    <article class="artCreature">

        <img src="img\bestiaire\Cuirassé.png">

        <p>
            Poisson de la taille d'un cheval dont le dos est recouvert d'une épaisse carapace. Ce prédateur des mers affectionne les humains 
            qu'il réduit en bouillie à l'aide de sa gueule imposante garnie de crocs qui sont capables de broyer le bois et le fer. La seule 
            faiblesse du poisson sont ses yeux que tout bon pêcheur apprent à viser au harpon. Sa chair est ferme et délicieuse, ce qui en 
            fait un met de choix qui se vent à un prix d'or.
        </p>

        <div class="divTemoin">
            <h3>"'Tention Matthieu, l'prochain s'ra un beau... Ça r'mue bien en tout cas ! Hein Mathieu... ? Mathieu... ?"<h3>
            <h4>Un pêcheur ayant perdu Mathieu lors d'une partie de pêche en mer</h4>
        </div>
    </article>
</section>

<h1 class="MenuH1">La suite du bestiaire prochainement !</h1>