<!-- TITLE -->
<h1 class="MenuH1">Fiche Personnage</h1>

<!-- PRESENTATION -->
<section>
    <article class="articleFiche">
        <p>Que serait une partie de jeu de rôle sur table sans fiche personnage ! Après tout, c'est le coeur même de vos notes que cela soit 
            au niveau des compétences, des points de vie, de l'inventaire de votre personnage et même de ses caractéristiques. 

            Bien que nous déplorons de ne pas avoir de fiche personnalisée à l'univers de Heilhem actuellement, nous nous basons sur la fiche
            connue et simple des Chroniques oubliés. Bien que nous n'utilisons pas certaines colones comme en lien avec les points de mana, 
            l'épuisement magie ou encore les points de récupération... Il s'agit là de la fiche la plus simple qui peut être adaptée à tout
            univers débutant !

            Celles plus connues de Pathfinder ou même de Donjon & Dragons sont plus complètes, mais aussi bien plus compliquée à comprendre.
            Ainsi, nous proposons à nos joueurs cette fiche pour la création de personnage et leur support lors des soirée Jeux de Rôle. Vous 
            pouvez simplement la télécharger en cliquant sur le bouton correspondant !
        </p>
    </article>

    <!-- FICHE IMG -->
    <div class="divImg">
        <img src="img\fiche\fiche_part_1.png" width="700px" height="1000px">
        <img src="img\fiche\fiche_part_2.png" width="700px" height="1000px">
    </div>

    <!-- BUTTON DOWLOAD -->
    <!-- <div class="btnFiche">
        <h2>Cliquez ici pour télécharger la fiche :</h2>
        <button type="submit">Fiche personnage</button>
    </div> -->
    
</section>
