<main>

    <!--ENTÊTE-->
    <section class="mainTete">
        <h1>Heilhem</h1>
        <h2>Répondez à l'appel du Destin</h2>
        
    </section>

    <section class="plateformeTete">
        <a href="https://discord.gg/Gx846WZS"><img src="./img/logo/discord.png" width="100px"></a>
        <a href="https://app.roll20.net/campaigns/details/7737395/call-of-helheim"><img src="./img/logo/dice.png" width="100px"></a>
    </section>

    <i class="fa-light fa-user-crown"></i>


    <!--INTRODUCTION-->
    <section>
        <article class="introduction">
            <p class="introP1">Imaginez un monde fantastique, empli de créature aussi beau que merveuilleux. Des monstres aussi hideux que démoniaque. 
                En général, vous jouez un aventurier prêt à occire toutes sortes de créatures malveillantes et peu ragoutantes dans un 
                paysage des plus extraordinaire. Où vos seules limites, c'est votre imagination.
            </p>

            <p class="introP2">
                Mais... Et si on inverse les rôles pour une fois ? Et si vous jouez un Non-Mort au sein d'un royaume reculé empli de mort-vivant,
                semi-démon, banshee et bien d'autres races que les personnes normaux de ce monde qualifie d'hérésie ? 
                Découvrez ainsi Heilheim et vous aussi, répondez à l'appel de votre destin !
            </p>

            <h2>Combattez l'hérésie qui rampe dans Mundos ou rejoignez la, faites vos choix !</h2>
        </article>
    </section>
        
    <!--CARROUSSELLE PAGES-->
        <!--A MODIFIER PROCHAINEMENT + RAJOUTER DES ANIMATIONS-->

    <section>
        <div class="block-container">
            <div class="block_Supplice"></div>
            <div class="block_Mokthar"></div>
            <div class="block_Heilheim"></div>
            <div class="block_Saurien"></div>
            <div class="block_Melodie"></div>
        </div>
    </section>

    <!--A MODIFIER PROCHAINEMENT + RAJOUTER DES ANIMATIONS-->

    <!--PRESENTATION-->
    <section>
        <article class="presentation">
            <h2>Qu'est-ce que Heilhem ?</h2>

            <p>Il s'agit d'un univers créer par deux personnes passionnées de Jeux de Rôle sur table depuis cinq ans. Ils ont donc eu l'idée de
                créer un univers bien particulier qu'ils adorent les univers très connus comme Donjon & Dragon ou encore Pathfinder 
                pour le genre.  
            </p>

            <p>
                Tout se déroule sur un monde appeler Mundos où règne divers royaumes tous différents des uns et des autres. Que cela soit
                par leurs traditions, leurs religions, leurs races ou même leur aspect. En effet, cela ressemble à un monde médieval fanstastique
                classique : des humains, des nains, des elfes, des orcs, etc... Toutefois. Il ne faut pas se fier à cela, car les hérésies sont aussi 
                monnaies courantes dans ce monde : morts-vivants, semi-démon, tieffelins, mages pratiquant la magie noire... 
            </p>

            <p>
                Ce beau monde se retrouve généralement - pour les bien élevés d'entres eux - à Heilhem, le royaume et la capitale des 
                Non-Morts. Avec à sa tête, une personne que l'on surnomme le "Seigneur Protecteur". Une divinité qui cherche à rallier tous les 
                Non-Morts et ceux qui sont persécutés par les autres royaumes les traitants d'hérétiques ou de monstre. Pourtant, ces mêmes 
                hérétiques semblent défendre bien des causes notamment la paix de Mundos. Qui aurait pu croire que votre voisin qui est 
                un démoniste ou un ancien mage d'une cour Royale chercherait à sauver le monde et les fesses de ceux qui les persécutent.
            </p>

            <p>
                Dans cette pensée, il y a donc une question philosophique : " Qui est le monstre en ce bas monde ? "
            </p>
        </article>
    </section>

</main>