<!-- TITLE -->
<h1 class="MenuH1">Informations sur le jeux de rôle</h1>

<!-- CONTENT -->
<Section class="sectionJDR">
    <h2>Le jeux de rôle, comment ça marche ?</h2>

    <!-- PRESENTATION -->
    <article class="artJDR">
        <h3>
            Dans un premier temps, un peu de culture général s'impose. 
        </h3>

        <p>
            Le premier jeu de role existe depuis 1974 avec le premier Donjon et Dragon créer par Gary Gygax. Le livre est si connu dans
            ce domaine qu'il est actuellement le plus connu et populaire du genre. Il fait parti de manière intégrante à ce qu'on appelle la 
            "Pop Culture". Qu'il soit cité dans des livres de littérature, films ou bien qu'il inspire d'autres jeux de rôle du genre. On peut
            le qualifier d'incontournable pour ceux qui s'intéresse à ce domaine. 
        </p>

        <h3>
            Le principe du jeu de rôle ? 
        </h3>

        <p>
            Il y a plusieurs manières de faire du jeu de rôle. Cela peut passer par de l'écrit sur différents forums ou autres supports comme 
            discord, les jeux vidéos, des livres (pour citer "Le livre dont vous êtes le héro" ou "Les aventures du Pyro Barbare et de Billy "), 
            et bien d'autres supports. mais aussi de manière orale dans un environnement dédié comme les jeux de rôles sur table ou en GN 
            (jeux de rôle en Grandeur Nature). 

            Toutefois, le principe est le même pour tous. Vous incarnez un personnage que vous avez imaginez que cela soit par son caractère,
            son physique et même ses caractéristiques (Nous reviendrons sur ce sujet un peu plus tard). Vous faites évoluer votre personnage
            dans un monde construit où vous faites votre jeu de rôle (médieval, fantastique, futuriste, survivaliste, dystopie, etc). Lorsque 
            le Maître du jeu ou le Game Master en anglais qui s'occupe de votre aventure où vous évoluez et jouez avec vos amis / compagnons,
            vous êtes amener à réfléchir comme votre personnage que cela soit par sa façon de parler et d'agir en fonction des évenements et 
            de l'environnement où se trouve votre personnage.
        </p>

        <h3>
            Qu'est-ce que c'est, les caractéristiques d'un personnage ?
        </h3>

        <p>
            Il existe différentes caratéristiques importantes d'un personnages mais qui sont généralement les mêmes. Attention ! Certains jeux de rôle 
            n'utilisent pas toutes les caractéristiques générales. C'est grâce à elles en fonction de vos points dédiés dans ces dernières et un dé
            que vous allez déterminé la réussite ou les échecs de vos actions. Nous pouvons donc y trouver : 
        </p>   
        
        <ul class="ulJDR">
            <li>La force</li>
            <li>La dextérité</li>
            <li>La constitution</li>
            <li>L'intelligence</li>
            <li>La sagesse</li>
            <li>Le charisme</li>
        </ul>

        <p>
            Comme cité plus haut, il existe certaines caractéristiques utilisée ou non en fonction des jeu de rôle. Pour le jeu de rôle connu 
            sous le nom de l'appel de Cthulhu (créer en 1981 par Sandy Petersen qui s'inspire de la nouvelle du même nom de H. P. Lovecraft) vous avez
            la caractéristique "Santé mentale" qui est très importante.
        </p>

        <h3>Maintenant que vous connaissez un peu plus de chose sur le jeu de rôle, nous pouvons passer aux compétences d'Heilhem</h3>
    </article>

    <!-- INFORMATIONS-->
    <h2>Informations basiques</h2>

    <article class="artJDR">
        <p>
        Les compétences sont des % à ajouter à vos statistiques de base. Elles vous permettent d’utiliser le savoir-faire de votre personnage pour 
        accentuer les chances de réussite d’une action ou de rendre possible des actions.

        Par exemple: Brug voudrait crocheter une serrure, il devra utiliser sa statistique de physique qui est de 50 ainsi que sa compétence 
        crochetage qui est à 15%. Brug doit donc faire une réussite à 65 ou moins pour réussir son crochetage.

        Les compétences vont de 5 à 20%. Lors de la création d’un personnage, le joueur commence avec 4 compétences de son choix à 5%. Il en 
        gagnera avec les niveaux ou en les utilisant souvent. Il est possible de faire une action sans en avoir la compétence.

        Par exemple: L’équipe entre dans une caverne. Le MJ demande un jet de perception pour tous les membres. Ceux avec la compétence de 
        “Perception” auront un avantage, mais ne réussiront pas forcément s’ils font un mauvais jet.La Magie est comprise dedans, tout mage 
        commence avec la compétence “Maîtrise Magique”. Elle évolue à chaque niveau du mage, accordant son bonus. Une fois au niveau quatre, 
        le mage a atteint son bonus maximum avec 20%.
        </p>
    </article>

    <!-- DICES-->
    <h2>Fonctionnement des dés</h2>

    <article class="artJDR">
        <p>
            Chaque action demandera un jet (1D100), le joueur se base sur sa statistique de Physique, Mental ou Social. Il y ajoute le % de 
            compétence pour connaître sa limite.

            Le jet peut être réussi s’il est en dessous de la limite, échouer s’il l’a dépassé.

            Une Réussite Critique est entre 1 et 5 (Inclu). Il s’agit d’une réussite absolue d’une action qui avantage le joueur ou l’équipe.
            Un Échec Critique est son contraire, on considère un EC si c’est un 96 ou plus. Il s'agit d’un échec total qui désavantage 
            grandement le joueur ou l’équipe. Plus le jet s’approche d’un extrême, plus la réussite/l’échec est grand.
        </p>
    </article>
</Section>