<!--TITLE-->
<h1 class="MenuH1">Mundos et son lore</h1>

<!--SOUS-MENU-->
<Section>
    <div class="subMenuRace">
        <ul>
            <li><a href="/?page=religion">La religion de Mundos</a></li>
            <li><a href="/?page=race">Les différentes races</a></li>
        </ul>
    </div>
</Section>

<!-- TITLE -->
<section class="mapSection">
    <article class="introduction">
        <h2>Carte officielle de Mundos</h2>
        <p>
            Mundos est composé principalement de quatre continents. Tous étant aussi différents les uns que les autres par leurs cultures, la faune,
            la flore ainsi que les individus qui y résident. Vous aurez sans aucun doute l'occasion de parcourir ces terres afin de connaître
            leurs secrets et les surprises qui s'y terrent. 
        </p>
    </article>

    <div class="mapDecoration">
        <img src="img\map\Mundos.png" width="1000px">
    </div>
</section>

<section class="mapSection">
    <article class="introduction">
        <h2>Helheim</h2>
        <p>
            Helheim est la Terre des Non-Morts, ceux qui sont revenus des Limbes pour hanter Mundos. Ce sont ceux qui se sont dressés contre 
            le Fléau Noir car à leurs armées. Bien des peuples craignent ou sont curieux de ces terres qu’on dit maudites. On ne connaît que l’île 
            où ils se trouvent et où se trouve la capitale de la Nécropole. La Cité est en partie souterraine et ce n’est que très récemment que la 
            ville a commencé à s’étendre en surface.
        </p>
    </article>

    <div class="mapDecoration">
        <img src="img\map\Helheim.jpg" width="800px">
    </div>
</section>

<section class="mapSection">
    <article class="introduction">
        <h2>Les quinzes royaumes</h2>
        <P>
            Les Quinze Royaumes sont un rassemblement de royaumes dirigés par les Occids qui se trouve à l’extrême ouest de Mundos. Chaque Cité État 
            est dirigée par un Régent et tous obéissent au Haut-Roi qui régit depuis la Forteresse de Khan où siège aussi l’Inquisition du Soleil 
            d’Or. Lors des grandes décisions ou quand vient le temps de choisir un nouveau Haut-Roi, les Régents et leurs mages attitrés se 
            réunissent au Conseil des Quinze pour voter ces fameuses décisions.
        </P>
    </article>

    <div class="mapDecorationQuinze">
        <div class="quinzeMapZoom">
            <img src="img\map\QuinzeOuest.png" width="800px">
        </div>
        <div class="quinzeMapZoom">
            <img src="img\map\QuinzeEst.png" width="800px">
        </div>
    </div>
</section>

<section class="mapSection">
    <article class="introduction">
        <h2>Les Royaumes de Fer</h2>
        <p>
            Les Royaumes de Fer, aussi appelé les Terres de Sang, sont un immense marécage empli de créatures dangereuses et de pièges mortels. 
            Ces terres ont été témoins de la grande bataille pour repousser le Fléau Noir. Le sang a tant coulé qu’il a transformé le sol et 
            que l’odeur métallique du sang est continuellement présente dans l’air, d’où le nom de cet endroit où le soleil ne brille jamais et 
            qui est devenu le repaire des Lycanthropes et des Vampires.
        </p>
    </article>

    <div class="mapDecoration">
        <img src="img\map\Fer.png" width="800px">
    </div>
</section>

<section class="mapSection">
    <article class="introduction">
        <h2>Les Rocailles arides</h2>
        <p>
            La Ménagerie est une oasis de bien-être au cœur des Rocailles Arides, une terre sèche où rien ne pousse et qui est connue pour 
            ses fauves et ses tempêtes de roches mortelles. Ménagerie est le berceau des Hommes-Bêtes, un lieu de rêve pour ceux qui ont 
            tant cherchés un foyer qui leur était refusé dans le passé.
        </p>
    </article>

    <div class="mapDecoration">
        <img src="img\map\Rocailles.png" width="800px">
    </div>
</section>

<section class="mapSection">
    <article class="introduction">
        <h2>Terres de l'Est (Plateaux Inférieurs)</h2>
        <p>
            Les Terres de l’Est est une terre paisible où les habitants prient le Dragon D’Or Shinryu. Parsemée de plaines, de rivières et 
            de montagnes, ces terres sont connues pour leurs combattants mais aussi pour leur soie et leur médecine avancée. De plus, leur 
            continent ressemble à un dragon.
        </p>
    </article>

    <div class="mapDecoration">
        <img src="img\map\Est.png" width="800px">
    </div>
</section>

<section class="mapSection">
    <article class="introduction">
    <h2>Les îles obscures</h2>
    <p>
        Les Îles Obscures sont un Archipel où était implanté un puissant Royaume à la flotte navale puissante. Cette dernière a été détruite 
        par les pirates il y a trois cent ans. La mort et la douleur qui se sont dégagées de ces évènements ont ouvert des brèches dans 
        la barrière entre Mundos et les Limbes.

        Aujourd’hui, cet archipel est hanté par le Brouillâmes, la manifestation des morts sous la forme d’une brume épaisse, mais aussi par 
        les morts et la flotte mort-vivante qui attaque tout individu qui s’en approche.
    </p>
    </article>

    <div class="mapDecoration">
        <img src="img\map\Obscure.png" width="800px">
    </div>
</section>

<h1 class="MenuH1">Plus de cartes prochainement !</h1>
