<!--TITLE-->
<h1 class="MenuH1">Les différents peuples de Mundos</h1>

<!--SOUS-MENU-->
<Section>
    <div class="subMenuRace">
        <ul>
            <li><a href="#Nords">Les Nords</a></li>
            <li><a href="#Occids">Les Occids</a></li>
            <li><a href="#Estirs">Les Estirs</a></li>
            <li><a href="#Sudirs">Les Sudirs</a></li>
        </ul>
    </div>
    <div class="subMenuRace">
        <ul>
            <li><a href="#Arids">Les Arids</a></li>
            <li><a href="#Betes">Les Hommes-Bêtes</a></li>
            <li><a href="#SemiO">Les Semi-Orcs</a></li>
            <li><a href="#SemiD">Les Semi-Drows</a></li>
        </ul>
    </div>

    <div class="subMenuRace">
        <ul>
            <li><a href="#Elfes">Les Elfes</a></li>
            <li><a href="#SemiE">Les Semi-Elfes</a></li>
            <li><a href="#Nains">Les Nains</a></li>
            <li><a href="#NonM">Les Non-Morts</a></li>
        </ul>
    </div>
</Section>

<!--RACES-->
<section class="sectionRace">
    <!--HUMAINS-->
    <article class="artRace">
        <h2>Les Humains</h2>
        <p>
            Espèce la plus courante sur Mundos, les Humains sont polyvalents et experts dans l’exploration. Voyageant sans cesse pour 
            découvrir, ils sont des alliés de choix et un peuple fier. Chaque peuple a ses propres croyances.
        </p>
    </article>

    <!--NORDS-->
    <article id="Nords" class="artRace">
        <h2>Humains du Nord (Les Nords)</h2>
        <p>
            Les Nords possèdent une force et une résistance améliorées dues aux difficultés de vie dans le Grand Nord. Ce sont des guerriers 
            qui ne craignent ni la mort ni la souffrance. C’est vivre ou mourir en se battant. Le peuple est divisé en clans, chacun dirigé 
            par un Jarl, tous obéissent au Haut-Jarl. 
        </p>

        <h3>Espérance de vie</h3>
        <p>
             50 à 70 ans.
        </p>

        <h3>Culte</h3>
        <p>
            Leur peuple est fondé sur le respect des Aînés, des Défunts et des Dieux Dragons. Pour eux, mourir au combat est un aller 
            simple vers le Domaine des Dieux où ils festoient pour l’Éternité.
        </p>

        <h3>Affinité avec la magie</h3>
        <p>
            La magie est pour eux mal vue car il s’agit d’un pouvoir réservé aux dieux. Les mages non approuvés par 
            les Dieux sont donc peu appréciés car il s’agit de mortels maniant des pouvoirs qui les dépassent. Cependant ils utilisent volontiers 
            des armes runiques, les Nords sont en effet des runistes expérimentés.
            De plus, les plus sages des Nords sont choisis dès la Naissance par les Dieux, leur accordant une maîtrise des éléments qui en font 
            des Chamans.
        </p>

        <h3>Langues connues</h3>
        <p>
            Humain, Nord, Commun.
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Ils ne sont pas belliqueux de nature envers les autres races. Les seules exceptions sont les Elfes, 
            les Orcs et les Drows bien évidemment.
        </p>

        <h3>Traits</h3> 
        <p>
            Les Nords sont plus résistants que les autres races et peuvent porter des armures lourdes sans entraînement grâce à Corps de 
            Titan mais aussi manier des armes lourdes à deux mains sans être ralenti et sans malus. Cela leur permet aussi de soulever et de 
            manipuler des charges lourdes.
        </p>

        <p>
            Ils possèdent la compétence innée: Rage du Nord qui leur permet de doubler leurs dégâts durant 2 tours mais cela leur empêche 
            toute chance d’esquive ou de parade.Cependant, s’ils tombent à 0 PDV alors qu’ils sont en rage, ils peuvent faire deux jets de 
            survie au lieu d’un seul pour rester conscient.
        </p>
    </article>

    <!--OCCIDS-->
    <article id="Occids" class="artRace">
        <h2>Les Humains de l’Ouest (Les Occids)</h2>

        <p>
            Les Occids sont les humains de l’Ouest, le peuple peut-être le plus présent sur Mundos, ce sont des aventuriers et des explorateurs 
            de nature. L’Ouest est dirigé par les Chevaliers et les Quinze Royaumes. Il s’agit de quinze Royaumes qui se partagent l’ouest 
            de Mundos, chacun gouverné par un Régent qui dirige son propre royaume. Cependant, ils obéissent tous au Haut-Roi. 
            Quand le Haut-Roi meurt, les quinze Régents se réunissent pour élire le nouveau Haut-Roi parmi l’un d’eux. 
        </p>

        <h3>Espérance de vie</h3>
        <p>
            50 à 65 ans.
        </p>
            
        <h3>Culte</h3>
        <p>
            Les Occids croient au Grand Créateur Anodis, le Divin apporteur de la Lumière pure et saine et Père de l’Humanité.
            L’Ordre des Chevaliers est par ailleurs divisé en plusieurs branches:
            Les Chevaliers sont des guerriers liés à un Seigneur.
            Les Paladins sont des guerriers liés à l’Église de la Lumière.
            Les Prêtres et Prêtresses qui sont des représentants de haut-rang de leur culte. Maniant la magie de lumière sous la Juridiction 
            du Divin lui-même.
            Les Inquisiteurs sont des Paladins spécialisés dans la chasse et l'éradication des hérétiques. Si un Paladin peut faire preuve 
            de clémence, un Inquisiteur est intransigeant. 
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Ils sont ouverts à presque toutes les races humaines mais se méfient de certains comme les 
            Sudirs à cause de leur peau sombre et leurs pratiques étranges. Ils ont tendance à voir tout ce qui n'est pas humain de haut. 
            Ils traitent les Hommes-Bêtes comme des animaux, bien que certains soient appréciés parmi les humains. Les Orcs sont vus comme des 
            bêtes sauvages. Ils n'apprécient pas les Elfes et leurs rites ancestraux. Les fervents de la Lumière haïssent tout ce qui est à 
            leur yeux impurs et non humain, les Morts d’Helheim sont donc une hérésie pour eux.
        </p>

        <h3>Affinité avec la magie</h3>
        <p>
            Contrairement aux Nords, les Occids pratiquent la magie, bien qu’un mage soit rare et ne se promène 
            jamais sans raison, il existe des écoles de magie. Pour reconnaître un mage de haut rang, il faut observer ses épaulettes. 
            Des épaulettes de cuir signifient que le mage est un initié qui a débuté sa formation depuis quelque temps. Des épaulettes 
            garnies d’argent signifient que le mage est un mage accompli et qu’il maîtrise son domaine. Des épaulettes d’or, qui ne sont 
            données que suite à des années d’apprentissages, de voyages, de découvertes révolutionnaires ou de hauts-faits, signifient que 
            le mage est en passe de devenir Archimage.
        </p>

        <h3>Langues connues</h3>
        <p>
            Occid, Humain, Commun.
        </p>

        <h3>Traits</h3>
        <p>
            Les Occids possèdent la compétence innée: Voyageur Adapté qui leur permet de ne pas souffrir des intempéries lors de leurs 
            voyages.
        </p>

        <p>
            Ils peuvent par ailleurs utiliser Fin Fouineur pour lancer un dé pour récupérer du butin supplémentaire.
        </p>
    </article>

    <!--ESTIRS-->
    <article id="Estirs" class="artRace">
        <h2>Les Humains de l’Est (Les Estirs)</h2>

        <p>
            Par delà les forêts mystérieuses de l’Est, par delà les Montagnes des Cieux, on trouve les Estirs. Un peuple qui a voué sa vie à 
            la paix et au respect de leur Dieu Shinryu, le Grand Dragon des Cieux. Les moines combattants des Monastères vouent leur vie à 
            maintenir et propager cette paix si fragile. Préférant parler plutôt que de  se battre, ils n’hésitent cependant pas à combattre 
            quand le temps est venu. Leur corps est à l’image de leur esprit, souple comme le vent, fluide comme l’eau, intense comme le feu 
            et dur comme roc.
            Tous ne sont pas moines et il existe bien d'autres combattants dans les Terres de l'Est.
        </p>

        <h3>Espérance de vie</h3>
        <p>
            180 à 200 ans, on raconte que le Vénérable ancien, dirigeant de ce peuple, aurait 3000 ans.
        </p>

        <h3>Culte</h3>
        <p>
            Les Estirs prient le Grand Dragon des Cieux, Shinryu. Ils croient que le Grand Dragon vient les accueillir à leur mort pour 
            leur faire revoir leur vie et leur permettre de se réincarner après avoir laver leur âme du passé.
            Tous les moines viennent des Monastères et n’utilisent que leurs corps, ils ne s’autorisent aucune arme ni armure. Le corps est 
            une arme, leur esprit est un monastère.
        </p>

        <h3>Affinité avec la magie</h3>
        <p>
            Les Estirs n’utilisent pas la magie car elle a démontré qu’elle a toujours été utilisée avec de mauvaises 
            intentions. Les moines utilisent cependant l’énergie spirituelle du corps, le Ki. Renforçant leurs sens et leur corps, le Ki 
            permet aux moines de fendre la roche et de déchaîner une pluie de coups dévastateurs sur leurs opposants.(Utiliser 1 point de Ki 
            permet de donner un +2 (+ niveau du personnage) aux dégâts. La régénération de Ki se fait comme pour la magie mais est naturelle 
            de 1 point par tour.)
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Les Estirs n’entrent en conflit avec personne. Préférant voyager pour troquer leurs produits. 
            Ils agissent avec respect pour tous.
        </p>

        <h3>Langues connues</h3>
        <p>
            Estir, Humain, Bestial, Commun, Ancien.
        </p>

        <h3>Traits</h3>
        <p>
            Les Estirs sont entraînés physiquement mais aussi mentalement, grâce à Esprit Serein, ils ne sont pas affectés par les intrusions 
            mentales néfastes et les sorts de contrôle d’esprit. De plus, ils peuvent utiliser la Méditation pour se reposer plus rapidement et 
            récupérer des pv et des points de Ki. 
        </p>

        <h3>Les Estirs possèdent deux branches de combat</h3>    
        <p>
            Poing Dur : 
            Le Moine emploie son corps pour le rendre aussi dur que le roc pour infliger des coups lourds pour briser les os et 
            la pierre et même tordre le métal. Le Moine obtient alors Corps de Roc qui le rend naturellement plus résistant aux coups grâce 
            à son entraînement intensif (gagne 1 d'armure naturelle à chaque niveau) , cela lui permet de bloquer les coups et de détruire 
            des rochers ou des flèches sans en souffrir, mais aussi de briser des armures.
        </p>
        <p>
            Poing Souple : 
            Le Moine emploie son corps pour le rendre aussi rapide et insaisissable que le vent. Il déverse alors une multitude 
            de coups à sa cible. Le Moine obtient alors Danseur des Vents, lui offrant un bonus d’esquive et lui permet de dévier les 
            projectiles comme des flèches à mains nues. De plus, ils obtiennent +1 dégâts de base à chaque niveau et chaque attaque 
            est doublée. Grâce à leur vitesse, ils sont capables de donner deux coups au lieu d'un seul. 
        </p>
    </article>

    <!--SUDIRS-->
    <article id="Sudirs" class="artRace">
        <h2>Les Humains du Sud (Les Sudirs)</h2>

        <p>
            Peuple mystérieux et puissant, les Sudirs sont des humains qui ont conquis les jungles tropicales du Sud de Mundos. Terres 
            hostiles et créatures de cauchemars ont marquées les Sudirs jusqu’à leur peau, devenue sombre.  Ce sont des sages et de 
            puissants shamans qui parlent avec ceux du Monde des Esprits à l’aide de rituels inconnus.
        </p>

        <h3>Espérance de vie</h3>
        <p>
            50 à 70 ans
        </p>

        <h3>Culte</h3>
        <p>
            Les Sudirs écoutent et prient Naratys le Roc Immuable, Dieu de la Terre et du Savoir, son frère Neretys le Vent 
            Turbulent, Dieu du Vent et de la Liberté est surtout prisé par les Arids. Les cérémonies consistent en un sacrifice d’un 
            animal, dirigées par un chaman qui est alors “possédé” par l’un des Frères Divins le temps du rituel.
            Ils prient les Esprits des Bêtes, dont ils se tatouent le corps pour montrer leur affinité avec l’animal.
        </p>

        <h3>Affinité avec la magie</h3>
        <p>
            Les Sudirs partagent peu de choses avec leur savoir magique. Cependant, ils sont réputés pour manier la 
            magie de la terre ou de l’eau. Bien que les autres éléments soient utilisés. Ils sont cependant connus pour leurs 
            tatouages, des tatouages infusés de magie qui permettent aux Sudirs de manier la puissance d’un animal esprit.
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Les Sudirs sont ouverts aux humains sans aucune arrière pensée, marchandant et voyageant 
            volontiers pour faire du troc. Cependant, ils n’apprécient guère les autres nations. Orcs, Drows et Elfes sont mal vus car ils ne 
            sont que guerre et conflits selon leurs croyances. Les Hommes-Bêtes sont très appréciés par leur peuple grâce à leur lien avec 
            la Nature. De part leurs rituels, certains voient les Sudirs comme de sombres sorciers.
        </p>

        <h3>Langues connues</h3>
        <p>
            Sudir, Arid, Bestial, Humain, Commun.
        </p>

        <h3>Traits</h3>
        <p>
            Les Sudirs possèdent la compétence innée: Esprit Animal qui leur permet d’obtenir une capacité liée à leur animal totem.
            Ils peuvent par ailleurs utiliser le Sens des Esprits pour affiner leur perception (15% bonus) que ce soit de la perception 
            classique (physique) ou magique (mental),dépendant si l’individu est mage ou non.
        </p>
    </article>

    <!--ARIDS-->
    <article id="Arids" class="artRace">
        <h2>Les Humains du Désert (Les Arids)</h2>

        <p>
            Peuple qui a su dompter les vents de la Mer de Sable, ce sont des nomades qui naviguent sur le sable à l’aide de navires plats sur 
            roues, poussés par le vent au fil des jours, ne s’arrêtant que sur les rares oasis du désert, les bateliers ont un rôle important 
            car ils doivent naviguer avec une centaine de personnes, souvent des familles complètes. Ils sont fiers, désinvoltes, prompts 
            au rire et à tout voir du bon côté, se vantant de leur liberté absolue. Beaucoup ont quitté le désert pour naviguer sur les 
            mers, ce sont des marins reconnus et des combattants agiles. Ils aiment arborer des tatouages qui sont des signes 
            d'appartenance et racontent leurs histoires, en effet, un Arid âgé est couvert de tatouage car à sa mort, il aura l’honneur 
            de raconter son histoire à Neretys, Le Vent Turbulent.
        </p>

        <h3>Espérance de vie</h3>
        <p>
            50 à 60 ans
        </p>

        <h3>Culte</h3>
        <p>
            Les Arids vouent leur vie à leur liberté et qui répond mieux à cela que Neretys le Vent Turbulent, Dieu du Vent et de 
            la Liberté. Ils ne pratiquent aucun rituel et leurs prières sont muettes, souvent en hauteur à la faveur du vent. Leur 
            peuple est dirigé par le Conseil des Femmes, en effet, ce sont les femmes qui prennent les grandes décisions, leurs 
            histoires parlent en effet de la Sagesse des Femmes offertes par la Mère des Jumeaux Neretys et Naratys : Neralys, Dame Terre Mère.
        </p>

        <h3>Affinité avec la magie</h3>
        <p>
            Les Hommes du Désert sont peu à pratiquer la magie, préférant danser avec un sabre et naviguer. 
            Certains sont cependant d’excellents mages du vent, peut-être une affinité acquise auprès du Dieu Neretys.
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Étant nomades, les Arids qui restent dans le désert ont peu de lien avec les autres 
            nations, d’ailleurs, rares sont les étrangers à avoir la chance de monter sur leurs navires. Cependant, une fois leur 
            loyauté acquise, ce sont des compagnons d’aventures plaisants, très peu prompts à la panique ou au défaitisme.
        </p>

        <h3>Langues connues</h3>
        <p>
            Arid, Sudir, Commun.
        </p>

        <h3>Traits</h3>
        <p>
            Les Arids sont connus pour leur arrogance et leur désinvolture totale dûe à leurs talents: Prouesse Insolente leur 
            permet à chaque Réussite de donner un bonus à ses alliés sur leur prochaine action (5). Et en cas de  Réussite critique de 
            donner un bonus à ses alliés (10) sur leur prochaine action tout en donnant un malus du même degré aux ennemis pour leur prochaine 
            action. Cependant, en cas d’échec, la situation est inversée: Les alliés reçoivent un malus pour leur prochaine action (5) et en 
            cas d’Échec critique, les alliés ont un malus et les ennemis ont un bonus à leur prochaine action(10).
            Négoce et Acquisition est un deux en un, ce trait donne aux Arids la possibilité d’avoir un bonus de 10% lors des 
            négociations, que cela soit pour convaincre quelqu’un ou marchander avec un commerçant. De plus, cela leur accorde un bonus au 
            Vol à la tire de 10% en plus de la compétence.
        </p>
    </article>

    <!--HOMMES-BÊTES-->
    <article id="Betes" class="artRace">
        <h2>Les Hommes-Bêtes</h2>
        
        <p>
            Les Hommes-Bêtes sont des animaux anthropomorphiques qui vivent en clan selon leurs espèces. Ils sont rares mais peuvent se 
            trouver partout dans le monde et principalement aux Rocailles Arides dans la Cité de Ménagerie. Chaque espèce bénéficie 
            d'attributs uniques venant de leur affinité animale. Ils peuvent par ailleurs communiquer avec les animaux grâce à leur 
            langage animal.
        </p>

        <h3>Espérance de vie</h3>
        <p>
            Selon leur espèce allant de 50 à 300 ans.
        </p>

        <h3>Culte</h3>
        <p>
            Diffère selon les Clans. Ils prient cependant Nihilis, Déesse de la Nature et Mère Nourricière ainsi qu'Orobos, Père 
            Créateur. 
        </p>

        <h3>Affinité avec la magie</h3>
        <p>
            Les Hommes-Bêtes sont capables de manier toutes les magies, ils sont spécialisés dans une magie affiliée 
            à leur côté animal. Un Homme-Salamandre sera plus adapté à manier la magie de feu ou de poison. Là où un Homme-Buffle sera adapté 
            à la magie de terre. 
            Cependant le druidisme est le plus courant dans leur culture.
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Les Hommes-Bêtes apprécient les Sudirs et les Elfes. Ils s’entendent relativement bien avec 
            les Nords. Par contre, ils se cachent du regard des Occids.
        </p>

        <h3>Langues connues</h3>
        <p>
            Bestial, Commun.
        </p>

        <h3>Traits</h3>
        <p>
            Grâce à leur Côté Bestial, les Hommes-Bêtes bénéficient de capacités animales selon leur espèce. Leurs capacités physiques 
            et sensorielles en sont affectées, parfois contre eux car leur odorat trop puissant est souvent victime de la puanteur.
            Ils possèdent aussi Sens Bestial qui leur permet, seulement quand ils sont attaqués ou en danger, de bénéficier d’un bonus de 
            10 à leurs actions.
        </p>
    </article>

    <!--SEMI-ORCS-->
    <article id="SemiO" class="artRace">
        <h2>Les Semi-Orcs</h2>

        <p>
            Nul ne peut égaler un Orc sur le domaine de la guerre et de la sauvagerie, même à moitié mort un Orc se battra jusqu'à son dernier 
            souffle. Les Semi-Orcs sont le plus souvent le fruit d’un accouplement involontaire entre une humaine et un Orc. On compte deux 
            types de Semi-Orcs, les Semi-Orcs verts, qui sont plus fréquents. Et les Semi-Orcs noirs, plus rares et plus puissants. Les 
            Semi-Orcs ne sont que peu appréciés par les leurs et encore moins par les humains car ils représentent le fruit d’un viol.
        </p>

        <h3>Espérance de vie</h3>
        <p>
            70 à 90 ans
        </p>

        <h3>Culte</h3>
        <p>
            Ils peuvent prier les Dieux humains comme les Esprits Orcs. Cependant ils n’affichent jamais leurs croyances, cela se limite 
            à une prière mentale ou un petit talisman en pierre ou en os.
        </p>
        
        <h3>Affinité avec la magie</h3>
        <p>
            Les Semi-Orcs peuvent manier toutes les magies élémentaires et ont une affinité avec les bêtes. En effet, ce 
            sont d’excellents chasseurs qui montent le plus souvent un Grand Loup des Montagnes et leurs shamans sont connus de partout. 
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Apprécient les Hommes-bêtes et certains humains. Principalement ceux avec qui ils font équipe. Ils 
            n’apprécient guère les elfes ainsi que les Orcs purs car ils sont traités comme des esclaves.
        </p>

        <h3>Langues connues</h3>
        <p>
            Humain, Orc, Drow, Commun.
        </p>

        <h3>Traits</h3>
        <p>
            Les Semi-Orcs bénéficient d’une partie de la force de leur côté Orc et leur permet d’utiliser Douleur du Berserker. Quand ils 
            sont à 50% de leur vie, les Semi-Orcs bénéficient d’un bonus  et peuvent doubler leurs dégâts. L’effet disparaît quand ils récupèrent 
            des points de vie.

            Ami des Bêtes leur permet de débuter l'aventure avec un compagnon animal et leur donne un bonus de 10% pour le domptage en plus de la 
            compétence à côté. D’ailleurs, la régénération liée à la nourriture, bien que moindre, est toujours active. Grâce à Appétit du 
            Guerrier, les Semi-Orcs peuvent lancer un dé pour savoir le nombre de pdv rendu quand ils mangent un aliment là où un autre a 
            besoin de repos ou de soin.
        </p>
    </article>

    <!--SEMI-DROWS-->
    <article id="SemiD" class="artRace">
        <h2>Les Semi-Drow</h2>

        <p>
            Un autre fruit de la cruauté de la Guerre Noire. Les Drows sont la lie du monde, la vermine des profondeurs, tueurs, violeurs, buveur 
            de sang. Les Drows et leurs armées ont failli détruire les autres races de Mundos il y a des centaines d’années et cela a laissé 
            des marques dans l’esprit des peuples. Les Drows ne sont appréciés par personne et les Demi-Drows sont malheureusement mal traités.
            Les Drows sont un peuple Matriarcal, les femmes sont plus fortes, plus puissantes et dirigent les mâles. La seule exception est 
            le Porte-Parole qui ne plie le genou que devant la Reine Noire. 

            On reconnaît un Semi-Drow à la couleur de ses yeux et à la couleur de sa peau. Un Drow est plus sombre et a les yeux rouges.
        </p>

        <h3>Espérance de vie</h3>
        <p>
            1400 à 2500 ans.
        </p>

        <h3>Culte</h3>
        <p>
            Les Drows prient les Dieux des Profondeurs et Dieux Anciens, principalement la Reine Noire. Les Demi-Drows eux prient 
            certes ces dieux mais peuvent aussi prier les Dieux Humains.
        </p>

        <h3>Affinité avec la magie</h3>
        <p>
            Les Demi-Drows sont libres de maîtriser tous les types de magie, seuls les plus anciens peuvent manier 
            les magies avancées comme la Magie de Sang. 
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Très mauvaise, ils ne sont appréciés que par peu de gens. Ils se cachent la plupart du temps ou 
            portent des masques. Les Drows traitent les bâtards comme des esclaves.
        </p>

        <h3>Langues connues</h3>
        <p>
            Drow, Orc, Humain, Elfe, Ancien, Commun.
        </p>

        <h3>Traits</h3>
        <p>
            Grâce à Pas de l’Ombre, les Demi-Drows sont plus agiles mais aussi plus légers, leur permettant de marcher sur les pièges 
            et autres plaques de pression sans les activer. (Bonus de 10% en discrétion en plus de la compétence) 
            Leurs affinité avec l’obscurité permet aux Semi-Drows d’utiliser Oeil de l’Ombre qui leur permet de voir dans le noir et de 
            repérer le décor malgré l’obscurité.

            Le sang est par ailleurs un composant essentiel dans leurs rituels, les Demi-Drows peuvent boire quelques gouttes de sang pour 
            obtenir un bonus sur une action grâce à Bénédiction Sanguine (10 pour trois tours) . Le sang peut être animal.
        </p>
    </article>

    <!--ELFES-->
    <article id="Elfes" class="artRace">
        <h2>Les Elfes</h2>

        <p>
            Les Elfes sont un peuple ancien et divisé en classes diverses mais avec un trait commun, leur orgueil. Un Elfe fera toujours mieux 
            qu’un individu étranger. Les Elfes des Profondeurs, les Drows, sont leurs némésis absolu. Les elfes sont des êtres vivants dans 
            les différents milieux qui les ont vu grandir qu'on peut diviser en peuples. Les elfes des forêts sont des chasseurs, des traqueurs 
            et des herboristes extrêmement doués, reconnaissables à leurs cheveux blonds ou roux, de très rares individus ont les cheveux blancs.
            Les elfes des villes sont des elfes qui ont tourné le dos à la nature pour vivre parmi les autres peuples, ils ont le plus souvent 
            les cheveux noirs.

            Les elfes de la Lune sont des elfes à la peau plus pâle et aux cheveux sombres ou argentés.
        </p>

        <h3>Espérance de vie</h3>
        <p>
            Entre 5000 et 5500 ans, ils ne subissent pas les effets des maladies.
        </p>

        <h3>Culte</h3>
        <p>
            Les Elfes croient aux signes dans les étoiles et les astres et écoutent la voix de la Nature. Les Drows et les Elfes de la 
            Lune se basent sur l'astre Lunaire. Les Elfes des Forêts et des Villes se basent sur le Soleil.
        </p>

        <h3>Affinité à la magie</h3>
        <p>
            Les Elfes maîtrisent la magie élémentaire avec une proximité surprenante, capable d’infuser leurs armes avec de 
            la magie, ils sont capables d’utiliser toutes les magies cependant la nécromancie est mal vue car elle va à l'encontre du cercle 
            de la Vie et de la Mort.
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Relation froide avec les Humains, surtout avec les Nords. Entente cordiale avec les 
            Hommes-Bêtes, les Orcs ne sont guère appréciés et les Drows sont abattus à vue. Ils sont peu enjoints à s’entendre avec les 
            Nains, mais on parle plutôt d'une rivalité. Ils peuvent se montrer hostiles avec les leurs, en effet, il existe bien des tensions 
            entre les peuples des Forêts et des Villes mais surtout avec les hybrides. Un hybride entre un elfe des Forêts et un elfe des 
            Villes aura un mélange de couleur au niveau des yeux et des cheveux, là où un hybride elfe-humain, aura des oreilles plus 
            courtes, plus rondes et des cheveux plus proches des couleurs humaines et les membres un peu moins grands. Les Elfes des 
            Villes sont moins regardant, en effet, pour eux un elfe reste un elfe, qu’importe s’il est hybride elfique ou pas.
        </p>

        <h3>Langues connues</h3>
        <p>
            Elfique, Humain, Commun, Ancien, Drow, Orc, Sudir, Arid, Nord, Estir, Occid, Nain.
        </p>

        <h3>Traits</h3>
        <p>
            Les Elfes peuvent utiliser Oeil de l’Ancien pour percevoir les dangers à longue distance (10% perception visuelle). De 
            plus, ils ont plus de facilité avec les arcs et les armes de lancer. (10% en plus de leur compétence d'archerie et de lancer) 
            Les Elfes peuvent utiliser Poussée de la Nature pour faire un bond de plusieurs mètres ou se déplacer sur des terrains accidentés 
            avec un bonus de 15, comprenant la course, le saut, les acrobaties et l’escalade.

            Les Elfes peuvent utiliser Infusion élémentaire qui leur permet d'ajouter durant 3 tours un effet secondaire à leurs armes 
            selon leur élément.
        </p>
    </article>

    <!--SEMI-ELFES-->
    <article id="SemiE" class="artRace">
        <h2>Les Semi-Elfes</h2>

        <p>
            Les enfants venant d’un accouplement entre un elfe et une humaine deviennent des Semi-Elfes, bien que peu appréciés par les 
            leurs, ils sont cependants bien vus par d’autres peuples car ils possèdent le point de vue des Humains et des Elfes mais aussi 
            qu’ils sont d’incroyables mages, souvent retrouvés dans des académies de magie ou en tant que Mage de Cour. Ils possèdent une 
            longévité moindre que leurs parents elfiques mais sont tout comme eux, immunisés aux maladies.
        </p>

        <h3>Espérance de vie</h3>
        <p>
            400 à 500 ans.
        </p>

        <h3>Culte</h3>
        <p>
            Étant entre deux peuples, les Semi-Elfes prient Anodis mais continuent de lire dans les étoiles. Ils sont cependant moins 
            portés sur la religion.
            Affinité à la magie: Exceptionnelle, les Semi-Elfes sont des mages puissants et redoutables, pouvant manier tout type de magie.
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Correctes, ils récupèrent cependant leur rivalité avec les Nains et les préjugés dus à leur 
            statut d’hybride, que ce soit chez les Elfes des Forêts et parfois les humains, surtout les Nords. Ils haïssent les Drows comme 
            leurs parents.
        </p>

        <h3>Langues connues</h3>
        <p>
            Elfique, Humain, Commun, Ancien, Drow, Orc, Sudir, Arid, Nord, Estir, Occid, Nain.
        </p>

        <h3>Traits</h3>
        <p>
            Élu de la Magie donne un bonus passif de 10% aux Semi-Elfes lors de la pratique de leur magie, qu’importe laquelle et à 
            quel niveau.

            Les Semi-Elfes peuvent utiliser Frappe Mentale pour infliger à un seul adversaire 5 dégâts (+ leur niveau de magie) gratuitement 
            en plus de leur action de combat, l’attaque ne peut être bloquée que par magie. Ils infligent alors un malus à l’adversaire sur 
            sa magie selon le bonus de magie du Semi-Elfe pendant 1 tour. (Exemple: Eledin est niveau 2, il inflige alors 7 dégâts et un 
            malus de 10% en magie à son adversaire) La compétence prend 3+1d3 tours à se recharger.
        </p>
    </article>

    <!--NAINS-->
    <article id="Nains" class="artRace">
        <h2>Les Nains</h2>

        <p>
            Force, endurance et petites jambes. Pour eux, une bande de brigands ne compte que pour un. Les Nains sont des guerriers et des 
            artisans dont la réputation n’est plus à faire. Une chose sacrée pour les Nains et qu’ils ont en commun avec les Nords: La 
            barbe, une barbe est sacrée et toujours bien entretenue, un nain sans barbe est souvent cause d’exil ou d’un pari perdu.
            Ils vivent sous les montagnes où leurs cités sont dirigées par des Rois.

            Des armes Légendaires ou péter des gueules? Il faut choisir!
        </p>

        <h3>Espérance de vie</h3>
        <p>
            150 à 180 ans.
        </p>

        <h3>Culte</h3>
        <p>
            Aucun, les Nains ne jurent fidèlement qu’à leur Roi et à l’Unité des Nains et à la science.
        </p>

        <h3>Affinité avec la Magie</h3>
        <p>
            Les Nains sont des artisans de talent, capables de lier le métal et la magie pour rendre leurs créations 
            légendaires. Une épée manufacturée naine est souvent un objet de grande valeur. Ils manipulent la magie de terre avec brio, bien 
            qu’ils peuvent manier d’autres éléments.
            Ils utilisent les pierres magiques dans leurs créations, armes, armure ou encore mécaniques pour les rendre plus puissantes. Par 
            ailleurs, à la perte d’un membre, un Nain se voit greffer un membre mécanique qui peut-être muni d’un ou de plusieurs 
            fonctionnalités.
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Plutôt bonne, bien que conflictuelle avec les Elfes. Ils n’apprécient pas les Drows car ce sont 
            des opposants à leurs affaires dans les profondeurs.
            Ils sont aussi méfiants avec Helheim car ils sont des rivaux au niveau commercial.
        </p>

        <h3>Langues connues</h3>
        <p>
            Nain, Commun, Ancien
        </p>

        <h3>Traits</h3>
        <p>
            Leur Peau de Pierre permet aux Nains de rendre leur peau aussi dure que le roc, ils bloquent la moitié des dégâts subis 
            (après avoir compté l’armure). Peau de Pierre dure trois tours et ne peut être réutilisé sans un temps de repos (2+1d3 par le Mj)
            Les Nains peuvent utiliser leur affinité avec la roche et les joyaux pour les manger. Manger des pierres leur permet de refaire 
            leurs forces mais aussi de récupérer plus rapidement Peau de Pierre.
            Si un Nain perd un membre il obtient Membre Mécanique qui lui permet d’ajouter des fonctionnalités à son arsenal. (Sauter plus 
            haut, porter plus de charge, frapper plus fort…)

            Ils sont les seuls à pouvoir commencer avec la compétence Ingénieur à 10%.
        </p>
    </article>

    <!--NON-MORTS-->
    <article id="NonM" class="artRace">
        <h2>Les Morts d’Helheim</h2>

        <p>
            Helheim est la terre des Morts. Dirigé par le Seigneur Protecteur, ce royaume est sorti de son isolement, depuis des milliers 
            d'années, il y a de cela cinq cents ans pour contrer l’Armée des Drows qui sévissait sur Mundos. A l’aide de ses Généraux et de 
            ses armées, le Seigneur Protecteur repoussa les Drows hostiles pour ramener la paix.
            Helheim regroupe les mort-vivants qui n'ont pas perdu leurs esprits et qui voyagent en quête d’un but ou du repos éternel. Helheim 
            accepte cependant bien des êtres, pas seulement les morts.

            Éternité pour Helheim.
        </p>

        <h3>Espérance de vie</h3>
        <p>
            Jusqu’à la destruction de l’âme de l’individu.
        </p>

        <h3>Culte</h3>
        <p>
            Helheim est sous la juridiction du Seigneur Protecteur Ghul’Da’Ban qui est selon les légendes un Dieu. Les habitants vouent 
            leurs foi envers celui qui garde la fine barrière entre le monde des vivants et les Limbes. Mais le Protecteur autorise tout autre 
            culte tant que cela ne porte pas préjudice aux habitants.
        </p>

        <h3>Affinité avec la Magie</h3>
        <p>
            Les Morts sont capables d’utiliser toutes les magies, certains capables de manier jusqu’à plusieurs écoles. 
            Helheim prône que le mal doit être contenu et que le mal peut vaincre le mal. Pour lutter contre les Nécromants qui 
            sévissent, Helheim prend en charge tout individu qui manie la nécromancie pour qu’il reste dans le droit chemin. Les Non-Morts 
            manient le flux de la vie et de la mort.
        </p>

        <h3>Affinité avec les autres peuples</h3>
        <p>
            Helheim se veut ouverte à tous et n’hésite pas à tendre la main aux autres peuples. Les 
            Chevaliers de la Lumière et les Inquisiteurs ne les apprécient cependant pas, les voyant comme des hérétiques. Ils restent cependant 
            hostiles envers les Drows à cause de la Guerre Noire qui oppose Helheim et les Drows, bien qu’on remarque un début d’entente 
            entre les deux Nations. Cependant mieux vaut rester cacher, un mort-vivant n’est pas forcément bien vu, surtout qu’il est rare de 
            les voir en dehors de leur Royaume.
        </p>

        <h3>Langues connues</h3>
        <p>
            Ancien, Commun. + Langue du vivant.
        </p>

        <h3>Traits</h3>
        <p>
            Les mort-vivants d’Helheim sont particuliers car ils ne peuvent mourir selon les normes habituelles. Détruire leur corps 
            n’est pas suffisant, il faut détruire jusqu’à leur âme. De plus, les flèches ne leur font aucun dégât s’ils sont sous la forme 
            d’un squelette. La magie de la lumière, censée soigner, est horriblement douloureuse pour eux. Pour se soigner, les Morts 
            mangent, aussi surprenant que cela puisse paraître, des aliments pourris et avariés et de la chair humaine, les aliments n'ont 
            cependant aucun goût. Ils peuvent aussi manger des aliments normaux. Ils peuvent boire du poison mortel et cela ne leur fait 
            rien, au contraire, cela les soigne et renforce leurs os.

            Les Fantômes ne peuvent saisir d'armes ou porter d'armures, cependant ils peuvent prendre le contrôle d'une armure pour l'utiliser 
            comme un corps de substitution. Un sort de lumière l'éjecte cependant de l'armure. 

            Le Mort-vivant, donc un zombie classique, est sensible au feu mais possède une résistance améliorée. De plus, perdre un membre ne 
            l'handicape pas car il peut se le recoudre ou utiliser un membre d'un autre ou d'une créature pour obtenir ses capacités. 

            Les Mort-vivants possèdent des doigts squelettiques ce qui leur permet de crocheter les serrures avec leur Toucher du Mort.
        </p>
    </article>
</section>