<!--TITLE-->
<h1 class="MenuH1 ReligionH1">Les religions de Mundos</h1>

<!--RELIGION-->
<section class="sectionReligion">
    <p class="introReligion">
        Les Hommes sont séparés en plusieurs nations, il en va de même pour leurs croyances. Chaque peuple a ses propres croyances et montre 
        leur foi de manières parfois complètement différentes, définissant jusqu’à leur mode de vie.
    </p>

    <!--OCCIDS-->
    <h2>Les Occids</h2>
    <article class="artReligion">

        <div class="divReligion">
            <p>
                Les Occids possèdent un Panthéon centré sur Anodis et ses frères angéliques, ces derniers ont affronté les Démons durant des éons avant 
                l’arrivée des Hommes. Les Archanges ne se différencient physiquement de leurs semblables que par trois paires d’ailes angéliques au 
                lieu d’une seule.
            </p>
        </div>

        <img src="img\religion\angel.png">
    </article>

    <!--NORDS-->
    <h2>Les Nords</h2>
    <article class="artReligion">

        <div class="divReligion">
            <p>
                Les guerriers du grand froid vouent leur vie et leur sang aux Dieux Dragons qui régissent les Royaumes du Nord. Cependant à ne pas 
                confondre avec l’ancien Peuple Draconique qui a été exterminé. Ceux qui réussissent les Épreuves des Dieux Dragons deviennent des 
                Walkiar, Guerrier Dragon en langue Nordique. 
            </p>

            <p>
                Il s’agit d’un titre honorifique qui s’accompagne d’un don d’une écaille du Dieu Dragon qui prouve le statut du guerrier et 
                qui l’autorise à manier l’élément de son Dieu. Ceux qui sont autorisés de naissance à pratiquer la magie sont les 
                Chamans, définis à la naissance par le sacrifice d’un animal au centre de plusieurs braseros et le sang versé sur le front de 
                l’enfant. L’Oracle qui préside le rituel aura alors une vision du Dieu Dragon affilié à l’enfant, cependant il ne doit pas 
                oublier les autres Divins, tous sont priés, bien que certains soient préférés à d’autres selon les régions des Royaumes du Nord. 
                Les Runistes travaillent aux côtés des Chamans lors de la bénédiction des Armes par les Dieux, leurs runes permettant de rendre 
                hommage mais aussi d’insuffler pouvoir et volonté dans l’arme.
            </p>
        </div>

        <img src="img\religion\dragon.png" width="508px" height="508px">
    </article>

    <!--ESTIRS-->
    <h2>Les Estirs</h2>
    <article class="artReligion">

        <div class="divReligion">
            <p>
                Les Estirs ne possèdent qu’une seule grande divinité, Shinryu, Grand Dragon d’Or qui veille sur leurs âmes avant et après la 
                réincarnation de ces dernières. Cependant, certaines sont priées comme divinités mais sont nombreuses et sont parfois affiliées à 
                une seule tâche mais toutes sont supervisées par le Grand Dragon d’Or. On parle alors d’esprits comme certains temples précis qui possèdent 
                un esprit gardien unique, souvent affilié à un animal.
            </p>

            <p>
                A l’inverse, certaines entités mauvaises agissent contre l’ordre établi, proches des démons, on les appelle Môghyo, ces derniers 
                pouvant prendre possession des vivants, des morts, des objets mais seuls les plus vieux et plus puissants peuvent prendre 
                directement forme physique.
            </p>
        </div>

        <img src="img\religion\dragonGold.png" width="500px" height="750px">
    </article>

    <!--ARIDS-->
    <h2>Les Arids</h2>
    <article class="artReligion">

        <div class="divReligion">
            <p>
                Les Arids vivent dans la Mer de sable au sud des Quinze-Royaumes, ils naviguent sans cesse sur leurs navires en toute liberté en 
                priant Neretys, le Vent Turbulent.
            </p>
        </div>

        <img src="img\religion\wind.png">
    </article>

    <!--SUDIRS-->
    <h2>Les Sudirs</h2>
    <article class="artReligion">

        <div class="divReligion">
            <p>
                Par delà la Mer de Sable, au confin des Jungles Tegandze, se cache un peuple au passé parsemé de mystères que seuls les fauves et 
                la flore de la forêt ont pu observer. Les Sudirs ne possèdent qu’une Divinité mais communique avec elle uniquement lors de rituels 
                où un chaman est possédé par cette dernière. Ils prient principalement les Esprits des Bêtes qui leur apportent leurs dons.
            </p>
            </div>
            
        <img src="img\religion\spirits.png">
    </article>

    <!--ELFES-->
    <h2>Cultes des Elfes</h2>
    <article class="artReligion">

        <div class="divReligion">
            <p>
                Les elfes ne possèdent pas de divinité en soit, ils se basent sur les Astres pour pratiquer la divination à l’aide de préparations 
                alchimiques mais aussi de cadrans spéciaux. Ils sont d’ailleurs spécialisés dans cet art et ceux qui ont dépassé les simples 
                prévisions sont nommés astromanciens, un art qui peut parfois être implémenté de magie. Contrairement à d’autres peuples, il 
                n’est pas rare que les elfes des forêts et des villes rendent visite à leurs cousins de la Lune pour demander des informations 
                sur ce qu’ils ont vu.
            </p>
        </div>
            
        <img src="img\religion\astre.png">
    </article>

    <!--DROWS-->
    <h2>Les Drows</h2>
    <article class="artReligion">

        <div class="divReligion">
            <p>
                Fut un temps où les Elfes des Profondeurs priaient eux aussi la Lune et les Étoiles. Mais il y a de cela plus de mille 
                ans, ces derniers se sont détournés pour prier une sombre divinité qui les dirige. Tous se souviennent d’elle, tous tremblent à 
                l’évocation de son nom car elle était celle qui mena le Fléau Noir jusqu’à la surface et qui faillit précipiter Mundos à sa fin.
            </p>
        </div>

        <img class="imgDrow"src="img\religion\Selena.png">
    </article>

    <!--HOMME-BÊTES-->
    <h2>Cultes des Homme-Bêtes</h2>
    <article class="artReligion">

       

        <div class="divReligion">
            <p>
                Les Hommes-Bêtes prient deux divinités principales Orobos et Nihilis, certains clans prient d’autres divinités mineures selon 
                leur espèce.
            </p>
        </div>

        <div class="imgBetes">
            <img src="img\religion\Nihilis.png" width="500px" height="750px">
            <img src="img\religion\Oroboros.png" width="508px" height="508px">
        </div>

    </article>

    <!--ORCS-->
    <h2>Culte des Orcs</h2>
    <article class="artReligion">

        <div class="divReligion">
            <p>
                Les Orcs vivent dans les montagnes au Nord des Quinze Royaumes. Ils sont divisés en clan qui se font continuellement la guerre et 
                s’étaient alliés aux Drows lors de l’Invasion. Eux aussi cherchaient à quitter leurs montagnes pour profiter des plaines verdoyantes 
                et du temps plus clément. Les Orcs ne prient pas de divinités mais les Esprits des Éléments, chacun représentant plusieurs aspects 
                de la vie. Les Chamans Orcs sont réputés pour leur maîtrise élémentaire, en faisant des sages, des chefs spirituels, des guides 
                mais aussi des gardiens.
            </p>
        </div>

        <img src="img\religion\orcChaman.png">
    </article>

    <!--NON-MORTS-->
    <h2>Culte des Non-Morts</h2>
    <article class="artReligion">

        <div class="divReligion">
            <p>
                Lorsqu’un individu quitte Mundos, son âme traverse la fine barrière qui sépare notre monde des Limbes, la Porte des  mes. On raconte 
                que les Limbes sont un immense marais où les âmes font leur dernier chemin vers le Puit des  mes, un lieu où les âmes sont lavées de 
                tout ce qu’elles étaient et renvoyées dans le Grand Tout où elles attendent de revenir sur Mundos pour vivre une nouvelle vie.
            </p>

            <p>
                Les mort-vivants sont des carcasses dont les âmes n’ont pas réussi à traverser les Limbes et qui ont peu à peu oublié ce qu’elles 
                étaient. Ils reviennent sur Mundos pour hanter les vivants.
            </p>

            <p>
                Les Non-Morts sont quant à eux des individus dont l’âme n’a pas pu traverser la Porte des âmes. Leur âme revient dans leur corps 
                et provoque chez eux un déboussolement, ces âmes perdues dans ce monde qui ne leur appartient plus sont souvent condamnées à 
                errer en évitant les mortels de peur d’être chassés et abattus car la mort ne les a pas voulu. Souvent à cause de remords ou que 
                la mort relève d’un évènement tragique.
            </p>

            <p>
                Une Divinité est chargée du cheminement des âmes dans Mundos et dans les Limbes, c’est elle qui veille sur le Puit des âmes et 
                sur son bon fonctionnement et c’est lui le dirigeant d’Helheim, le Domaine des Non-Morts.
                Lors de l’invasion des Drows, les peuples de Mundos se sont défendus du mieux qu’ils pouvaient mais le Fléau Noir était tel une 
                vague immense sur de frêles demeures de paille.
                De la brume et des mers, une armée émerge. Une île se dévoile aux mortels alors qu’il n’y avait rien auparavant. En son 
                sein, un peuple qui avait connu la mort et qui ne la craignait pas. Le Dirigeant d’Helheim avait décidé que sa nation devait 
                sortir du silence et protéger Mundos contre l’envahisseur. L’Éveil d’Helheim provoqua la fin du Fléau Noir.
            </p>
        </div>

        <img src="img\religion\Protecteur.png" width="500px" height="750px">
    </article>
</section>

<h1 class="MenuH1">Plus de détails prochainement !</h1>